sudo: false
language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
  - "5"
  - "6"
  - "7"
install: 
  - npm install
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3335a340a3ff62cee15f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false