sudo: false
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "5"
  - "6"
  - "7"
  - "8"
cache:
  yarn: true
install:
  - yarn install
  - npm install -g codecov
script:
  - yarn run test-coverage
  - codecov --file=coverage/lcov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3335a340a3ff62cee15f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
